CREATE OR REPLACE VIEW serverless_stable_82bi8w_catalog.data_entry.daily_report AS
SELECT
    stacking_date,
    `tons_rom` AS `ore_delivered_mining_rom_tons`,
    `tons_non_core` AS `non_core_tons`,
    `tons_core` AS `core_tons`,
    `nuton_wet_total_crushed` AS `ore_delivered_nuton_wet_total_crushed_tons`,
    `nuton_total_stacked` AS `total_stackedpreagglomerator_tons`,
    `p80_12_passing` AS `p80_stacked_avg_12_inc`,
    `p80_34_passing` AS `avg_34_inc`,
    `rom_raffinate_flow` AS `raffinate_rom_flow_gpm`,
    `rom_raffinate_cu_grade` AS `cu_grade_gl`,
    `rom_acid_cure_acid_grade_bf` AS `acid_bf_gl`,
    `rom_raffinate_acid_grade` AS `acid_af_gl`,
    `rom_acid_cure_rom_acid_pounds` AS `acid_cure_st`,
    `rom_raffinate_total_acid_pounds` AS `rom_raff_acid_st`,
    COALESCE(`rom_acid_cure_rom_acid_pounds`, 0) + COALESCE(`rom_raffinate_total_acid_pounds`, 0) AS `total_leach_acid_st`,
    `acid_sx_usage_short_tons` AS `total_sx_acid_st`,
    `rom_raffinate_total_cu_pounds` AS `total_cu_pounds_lb`,
    `nuton_raffinate_pad_flow` AS `nuton_flow_gpm`,
    `nuton_raffinate_cu_grade` AS `cu_grade_gl_1`,
    `rom_acid_cure_acid_grade_bf` AS `acid_bf_gl_1`,
    `nuton_raffinate_acid_grade` AS `acid_af_gl_1`,
    `big_f_acid_totalizer_short_tons` AS `acid_at_aggl_st`,
    `rom_acid_cure_total_acid_poundsaggl` AS `raff_acid_pounds_st`,
    COALESCE(`big_f_acid_totalizer_short_tons`, 0) + COALESCE(`rom_acid_cure_total_acid_poundsaggl`, 0) AS `total_acid_st`,
    `nuton_raffinate_total_cu_pounds` AS `total_cu_pounds_lb_1`,
    `nuton_acid_cons` AS `acid_cons_lbt`,
    `rom_pls_flow` AS `pls_rom_flow_gpm`,
    `rom_pls_cu_grade` AS `cu_grade_gl_2`,
    `rom_pls_acid` AS `acid_ph`,
    `rom_pls_acid_1` AS `acid_gl`,
    `rom_pls_total_net_cu_pounds` AS `total_cu_pounds_lb_2`,
    `nuton_pls_flow` AS `nuton_flow_gpm_1`,
    `nuton_pls_grade` AS `cu_grade_gl_3`,
    `nuton_pls_acid_1` AS `acid_gl_1`,
    `nuton_pls_acid` AS `acid_ph_1`,
    `nuton_pls_gross_acid_pounds` AS `acid_pounds_st`,
    `nuton_pls_total_net_cu_pounds` AS `net_cu_pounds_lb`,
    `combined_pls_total_flow` AS `combine_pls_flow_gpm`,
    `combined_pls_calc_grade` AS `cu_grade_gl_4`,
    `combined_pls_calc_acid_grade` AS `acid_ph_2`,
    `combined_pls_net_pound` AS `net_pounds_cu_lb`,
    `burro_pit_flow` AS `burro_pit_pls_flow_gpm`,
    `burro_pit_grade` AS `cu_grade_gl_5`,
    `burro_pit_lbs` AS `net_pounds_cu_lb_1`,
    `total_flow` AS `sx_flow_gpm`,
    `plant_feed_pls_j_pond_3_cu_plant_avg_from_70011001500` AS `cu_grade_gl_6`,
    `ppd_available_lb` AS `plated_lb`,
    `in_raffinate_lb` AS `in_raffinate_lb`,
    `fe_bleed_lb` AS `fe_bleed_lb`,
    `sx_recovery_` * 100 AS `sx_eff`,
    `sx_net_lb` AS `net_pounds_cu_lb_2`,
    `copper_cathode_harvested_total_cu_harvested` AS `cathode_harvest_lb`,
    `copper_cathode_harvested_grad_2_scrap` AS `scrap_lb`
FROM serverless_stable_82bi8w_catalog.data_entry.nuton_load_daily_real;
