command:
  - "uvicorn"
  - "main:app"
  - "--host"
  - "0.0.0.0"
  - "--port"
  - "8000"

env:
  - name: DATABRICKS_HOST
    value: "https://fevm-serverless-stable-82bi8w.cloud.databricks.com"
  - name: DATABRICKS_WAREHOUSE_ID
    value: "7bbb09542781a5c7"
